#index:
#    resource: "../src/Controller/Router.php"
#    prefix:   /
#    type:     annotation

index:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
    defaults:
        path: /hu
        permanent: true

home:
    path:   /{_locale}
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    defaults:
        template: 'home.html.twig'
    requirements:
        _locale: hu|en

materials:
    path:   /{_locale}/materials
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    defaults:
        template: 'materials.html.twig'
    requirements:
        _locale: hu|en

food:
    path:   /{_locale}/food
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    defaults:
        template: 'food.html.twig'
    requirements:
        _locale: hu|en

health:
    path:   /{_locale}/health
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    defaults:
        template: 'health.html.twig'
    requirements:
        _locale: hu|en

contact:
    path:   /{_locale}/contact
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    defaults:
        template: 'contact.html.twig'
    requirements:
        _locale: hu|en

partner:
    path:   /{_locale}/partner
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    defaults:
        template: 'partner.html.twig'
    requirements:
        _locale: hu|en